// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_SI39hUnZegYi4JM0tctmJgFwExJ_tw',
    appId: '1:940228927910:web:bfc1dfa60d310166cc6f67',
    messagingSenderId: '940228927910',
    projectId: 'fir-flutter-codelab-7e385',
    authDomain: 'fir-flutter-codelab-7e385.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-7e385.firebasestorage.app',
    measurementId: 'G-2MYJWX99ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq92PPL1tORZK1SDUSqTOLEDwq-_qO1kg',
    appId: '1:940228927910:android:ce91b78ce589c207cc6f67',
    messagingSenderId: '940228927910',
    projectId: 'fir-flutter-codelab-7e385',
    storageBucket: 'fir-flutter-codelab-7e385.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVXKwBC86VzksGafJjTVVgL6QvG8h7aPg',
    appId: '1:940228927910:ios:07c07c924b458b20cc6f67',
    messagingSenderId: '940228927910',
    projectId: 'fir-flutter-codelab-7e385',
    storageBucket: 'fir-flutter-codelab-7e385.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVXKwBC86VzksGafJjTVVgL6QvG8h7aPg',
    appId: '1:940228927910:ios:07c07c924b458b20cc6f67',
    messagingSenderId: '940228927910',
    projectId: 'fir-flutter-codelab-7e385',
    storageBucket: 'fir-flutter-codelab-7e385.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

}